exclude: 'app/assets/stylesheets/markdown_body.scss'

linters:
  HexNotation:
    style: uppercase

  LeadingZero:
    style: include_zero

  SelectorDepth:
    max_depth: 5

  NestingDepth:
    max_depth: 5

  PropertyUnits:
    enabled: false

  PropertySortOrder:
    enabled: false

  QualifyingElement:
    enabled: false

  SelectorFormat:
    enabled: false

  DeclarationOrder:
    enabled: false

  ColorVariable:
    enabled: false
